### ISSUE TITLE
Definir periodicidade dos posts

### ISSUE THREAD

**Issue by gfpoliva** [CocoaHeadsBrasil/CocoaHeadsMedium#1]
A periodicidade da entrega vai variar de acordo com a complexidade do post.

**Comment by Viniciuscarvalho** [comment]
Para termos posts constantes e bem feitos, poderíamos começar com a frequência de 15 em 15 dias?

**Comment by gfpoliva** [comment]
@Viniciuscarvalho seria uma boa! Eu acho que seria interessante deixar datas estipuladas. Por exemplo: um novo post todo dia 1 e 15 de cada mês.

**Comment by unnamedd** [comment]
Que tal de repente se tivéssemos 3 posts por mês ? 
Dia 1, dia 11 e dia 21 ?

O que acham da idéia ?

**Comment by Viniciuscarvalho** [comment]
Será que temos tantas pessoas dispostas a escrever um post a cada 10 dias? Seria muito bom..

**Comment by Viniciuscarvalho** [comment]
Criei um calendário galera, dêem uma olhada #6

**Comment by gfpoliva** [comment]
Periodicidade definida de 15 em 15 dias.
