### ISSUE TITLE
[README] Sobre o projeto

### ISSUE THREAD

**Issue by gfpoliva** [CocoaHeadsBrasil/CocoaHeadsMedium#2]
Elaborar uma descrição para o projeto com as informações necessárias para as pessoas saberem sobre o que se trata

**Comment by Viniciuscarvalho** [comment]
Vou mandar o PR aqui dessa issue.

**Comment by Viniciuscarvalho** [comment]
Vou jogar essa issue para a de elaboração de fluxo de postagem.
