### ISSUE TITLE
[README] Definir cronograma de postagem

### ISSUE THREAD

**Issue by gfpoliva** [CocoaHeadsBrasil/CocoaHeadsMedium#3]
Definir as datas para entrega de revisão e postagem.

**Comment by gfpoliva** [comment]
Minha proposta seria a seguinte: CASO a periodicidade #1 seja definida como semanal, podemos ter o seguinte fluxo (irei utilizar datas fictícias para exemplificar):
1. Definimos uma data na semana padrão para publicação e entrega de revisão. Para EXEMPLO, vou estipular quarta-feira
2. Na primeira quarta-feira do projeto (13/04), iremos receber post para revisão
3. Na segunda quarta-feira do projeto (20/04), o texto que chegou pra revisão do dia 13/04 é postado e o autor da próxima semana entrega o texto para revisão.
4. Na terceira quarta-feira do projeto (27/04), o texto que chegou pra revisão do dia 20/04 é postado e o autor da próxima semana entrega o texto para revisão.
5. LOOP :)

**Justificativas**
- 1 semana para ajustes de post é mais que suficiente
- sempre haverá um próximo post pois a obrigação é entregar em um dia um texto novo e uma revisão para o futuro texto

**Benefícios**
- Esse exemplo pode ser utilizado em qualquer periodicidade

**Comment by nobre84** [comment]
Na minha opinião, mesmo que demoremos a começar o lançamento dos textos, um período de ao menos 15 dias deveria existir entre uma entrega para revisão e este mesmo texto estar escalado para publicação. Para que no caso de alguma falha ou atraso, não gere um efeito cascata atrapalhando a todos (ou fique um furo na periodicidade).
Depois que acumulássemos ao menos uns 4 a 6 artigos, aí começaríamos a liberar.

**Comment by Viniciuscarvalho** [comment]
Os posts seriam liberados a cada 15 dias, mas para isso teríamos que ter o banco de artigos de no mínimo um mês, acho que é por aí mesmo @nobre84. Se todos concordarem, já deveríamos botar mão na massa e convocar e escrever os artigos!
